---
title: "markdown"
runtime: shiny
output: html_document
date: "2024-05-29"
---

```{r}
fluidPage(
  
  titlePanel("Exploration of Gayborhood Statistics across the US"),

  mainPanel(
    mainPanel(
      tabsetPanel(
        tabPanel("Introduction", plotOutput("plot")),
        tabPanel("Page 1", verbatimTextOutput("summary")),
        tabPanel("Page 2", tableOutput("table")),
        tabPanel("Page 3", tableOutput("table")),
        tabPanel("Conclusion", tableOutput("table"))
      )
    )
  )
)
```
### Here are two Shiny widgets

```{r echo = FALSE}
selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20)

sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
```

### ...that build a histogram.

```{r echo = FALSE}
renderPlot({
  hist(faithful$eruptions, probability = TRUE,
       breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)",
       main = "Geyser eruption duration")

  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```